#pragma once

#include "driver/gpio.h"

#define SDHS_FIRMWARE_VERSION "0.1.0"
#define SDHS_HARDWARE_REVISION "HW_MAIN_REV_A"

#define SDHS_CONTROL_TASK_PERIOD_MS 1000
#define SDHS_SENSOR_STALE_TIMEOUT_MS 5000

#define SDHS_I2C_PORT 0
#define SDHS_I2C_SDA_GPIO GPIO_NUM_8
#define SDHS_I2C_SCL_GPIO GPIO_NUM_9
#define SDHS_I2C_FREQ_HZ 100000

#define SDHS_HEATER_EN_GPIO GPIO_NUM_10
#define SDHS_FAN_PWM_GPIO GPIO_NUM_11
#define SDHS_FAN_TACH_GPIO GPIO_NUM_12
#define SDHS_LED_STATUS_GPIO GPIO_NUM_13
#define SDHS_LED_FAULT_GPIO GPIO_NUM_14

#define SDHS_TEMP_HARD_LIMIT_C 70.0f
#define SDHS_TEMP_COOLDOWN_COMPLETE_C 35.0f
#define SDHS_DEFAULT_MAX_CYCLE_SECONDS (8 * 60 * 60)

